services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:5050"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"